@LiquidApi_HostAddress = http://localhost:5133

GET {{LiquidApi_HostAddress}}/api/v1/artists?name=pink_floyd
Accept: application/json
###

GET {{LiquidApi_HostAddress}}/api/v1/artists/111259
Accept: application/json
###

GET {{LiquidApi_HostAddress}}/api/v1/artists/112045/albums?offset=10&limit=10
Accept: application/json
