services:
  liquidapi:
    image: ${DOCKER_REGISTRY-}liquidapi
    build:
      context: .
      dockerfile: LiquidApi/Dockerfile
    environment:
      - ConnectionStrings__SqlDatabase=Server=sql_express;Database=LiquidApi;User Id=sa;Password=user@123; Trust Server Certificate=True
    ports:
      - 10000:8080

  sql_express:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: liquid_api_sql_express
    environment:
      - ACCEPT_EULA=True
      - MSSQL_SA_PASSWORD=user@123
    ports:
      - 1533:1433